#index:
#    path: /
#    controller: App\Controller\DefaultController::index

addNumero:
    path: /apiService/numero
    controller: App\ServiceApp\Controller\NumeroController::addNumero
    methods: POST