#index:
#    path: /
#    controller: App\Controller\DefaultController::index

add:
    path: /api/person
    controller: App\PersonaApp\Controller\PersonaController::add
    methods: POST


addNumero:
    path: /apiService/numero
    controller: App\ServiceApp\Controller\NumeroController::addNumero
    methods: POST